# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-30 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('group', models.CharField(choices=[('B1', 'B1'), ('B1', 'B2'), ('B1', 'C1'), ('B1', 'C2')], max_length=3)),
                ('vallet', models.IntegerField()),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('subject', models.CharField(max_length=80)),
            ],
        ),
    ]
